Bd connector refactory
brch0x2a/virtual-academy pull request #1
Opened 2021-11-04 22:40 UTC by Fahrenheit99

# Modifications
* Refactor BD calls through the project

2021-11-04 22:42 UTC, Fahrenheit99 commented
![](https://github.trello.services/images/mini-trello-icon.png) [BD Connector Refactory](https://trello.com/c/zq32qwCQ/44-bd-connector-refactory)

2021-11-09 04:37 UTC, brch0x2a requested changes

2021-11-09 04:37 UTC, brch0x2a commented on app/module/branch_of_kwnoledge/routes.py
En general bien
Pero usted borro el metodo
branch_of_kwnoledge_all_all()
que retorna la lista de todas las ramas sin filtro a la hora de crear una clasificacion a la rama nose puede por que no carga la lisa al combo box,
esta vacio, este lo ocupamos en la vista de category_course_collection

2021-11-09 17:37 UTC, Fahrenheit99 commented on app/module/branch_of_kwnoledge/routes.py
El método al que usted se refiere fue hecho para probar la respuesta del dbconector con respecto a una consulta, actualmente esa consulta se puede hacer sin ese método, creo que por lo que hemos visto en la llamada el problema se debía al vanilla javascript en el fetching, podemos revisar lo en una llamada.

2021-11-12 04:01 UTC, merged